---
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-added-large-files
  - id: check-executables-have-shebangs
  - id: check-json
  - id: check-shebang-scripts-are-executable
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: forbid-new-submodules
  - id: mixed-line-ending
    args: [--fix=lf]
  - id: trailing-whitespace
- repo: https://github.com/sirosen/texthooks
  rev: 0.7.1
  hooks:
  - id: fix-smartquotes
  - id: fix-ligatures
  - id: fix-spaces
- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.37.1
  hooks:
  - id: yamllint
    args: [--strict]
- repo: https://github.com/DavidAnson/markdownlint-cli2
  rev: v0.18.1
  hooks:
  - id: markdownlint-cli2
    args: ["--fix", "--config", ".markdownlint-cli2.yaml"]
- repo: https://github.com/ansible/ansible-lint
  rev: v25.8.2
  hooks:
  - id: ansible-lint
    args: ["--skip-list=yaml,jinja"]
    stages:
    - manual
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.10.0.1
  hooks:
  - id: shellcheck
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v9.22.0
  hooks:
  - id: commitlint
    stages: [commit-msg]
    additional_dependencies:
    - '@commitlint/config-conventional@19.2.2'
    - '@commitlint/ensure@19.0.3'
    - 'commitlint-plugin-function-rules@4.0.0'
    args: ['--verbose']
