---
- name: Converge
  hosts: all
  gather_facts: false
  vars:
    unpack_location: /tmp/unpack_location
    archive_source: https://dl-cdn.alpinelinux.org/v3.21/releases/x86_64/alpine-minirootfs-3.21.3-x86_64.tar.gz
  tasks:
  - name: "Fetch and unpack archive"
    ansible.builtin.include_role:
      name: homelab_ops.archive.unpack
    vars:
      archive:
        url: "{{ archive_source }}"
        destination_path: "{{ unpack_location }}"
