---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
- name: instance
  image: ${MOLECULE_IMAGE:-"geerlingguy/docker-ubuntu2404-ansible:latest"}
  pre_build_image: true
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        config:
          ubuntu_url: $ubuntu_tarball_url
  playbooks:
    prepare: prepare.yml
verifier:
  name: ansible
