---
- name: Prepare
  hosts: all
  gather_facts: false
  vars:
    boot_path: "/mnt/boot"
  tasks:
  - name: "Create needed directories"
    ansible.builtin.file:
      path: "{{ boot_path }}"
      owner: root
      group: root
      mode: '0750'
      state: directory
