---
- name: "load-config | Read settings from file"
  ansible.builtin.slurp:
    src: "{{ config.cluster_bootstrap_secrets }}"
  register: initialize_k3s_host_settings
  no_log: true

- name: "load-config | Extract settings into facts"
  ansible.builtin.set_fact:
    "cluster_bootstrap_secrets": "{{ initialize_k3s_host_settings['content'] | b64decode | homelab_ops.k3s.from_properties }}"
  no_log: true
