---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:
  - name: "Configure ansible"
    ansible.builtin.include_role:
      name: homelab_ops.configure.ansible
    vars:
      ansible_config:
        ansible_core_version: 2.16.2
        dependencies:
        - name: jmespath
          version: 1.0.1
          params:
          - include-apps
        collections_requirements_file: "{{ MOLECULE_SCENARIO_DIR }}/input/requirements.yaml"
