---
- name: Generate test bootstrap configuration
  hosts: "{{ target | default('all') }}"
  become: true
  gather_facts: false

  pre_tasks:
  - name: Check that output path has been provided
    assert:
      that:
      - output_path is defined and output_path|length > 0

  tasks:
  - name: Create output path if not exists
    ansible.builtin.file:
      path: "{{ output_path }}"
      state: directory
      owner: root
      group: root
      mode: '0755'

  - name: Generate sample bootstrap configuration
    ansible.builtin.template:
      src: "{{ item }}.j2"
      dest: "{{ output_path }}/{{ item }}"
      owner: root
      group: root
      mode: '0600'
    loop:
    - cluster-bootstrap-secrets
    - flux-bootstrap-conf
    - flux-bootstrap-secrets
