---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
- name: instance
  image: ${MOLECULE_IMAGE:-"geerlingguy/docker-ubuntu2204-ansible:latest"}
  pre_build_image: true
  privileged: true
  user: root
provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
verifier:
  name: ansible
