---
# ubuntu version dependent configuration
kernel_cmdline:
  # baseline cmdline options that should be used (regardless of ubuntu version)
  baseline:
  - "cgroup_enable=cpuset"
  - "cgroup_enable=memory"
  - "cgroup_memory=1"
  - "swapaccount=1"
  - "plymouth.ignore-serial-consoles"
  ubuntu_release_specific:
    focal:
    - "elevator=deadline"
    - "net.ifnames=0"
    - "dwc_otg.lpm_enable=0"
    - "console=tty1"
    - "fixrtc"
    jammy:
    - "dwc_otg.lpm_enable=0"
    - "console=tty1"
    - "fixrtc"

additional_kernel_params: []

supported_filesystem_types: ['btrfs', 'ext4', 'vfat']
supported_ubuntu_releases: ['focal', 'jammy']
