---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
- name: instance
  image: ${MOLECULE_IMAGE:-"geerlingguy/docker-ubuntu2204-ansible:latest"}
  pre_build_image: true
  privileged: true
  user: root
  volumes:
  - /dev:/dev
  - /proc:/proc
  - /sys:/sys
  - ${MOLECULE_SCENARIO_DIRECTORY}:/tmp/test_scenario
provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
  inventory:
    group_vars:
      all:
        MOLECULE_SCENARIO_DIR: /tmp/test_scenario
verifier:
  name: ansible
