---
- name: "Check for mandatory variables definitions"
  assert:
    that:
    - system_root_mount_path is defined

- name: "Create temp location for fstab generator"
  ansible.builtin.tempfile:
    state: directory
  register: fstab_generator_dir
  changed_when: false

- name: "Prepare fstab generator"
  ansible.builtin.copy:
    src: "genfstab"
    dest: "{{ fstab_generator_dir.path }}/genfstab"
    owner: root
    group: root
    mode: "755"
  changed_when: false

- name: "Generate fstab from mounted filesystems"
  ansible.builtin.shell: |
    #!/bin/bash
    set -eo pipefail
    export FSTAB_FILE={{ fstab_generator_dir.path }}/fstab.generated
    export TAG={{ source_partition_identifier | upper }}
    {{ fstab_generator_dir.path }}/genfstab -t $TAG -f {{ system_root_mount_path }} {{ system_root_mount_path }} > $FSTAB_FILE
  args:
    executable: /bin/bash
  become: true
  changed_when: false

- name: "Remove system root path prefix for mounts"
  ansible.builtin.replace:
    path: "{{ fstab_generator_dir.path }}/fstab.generated"
    regexp: "^{{ system_root_mount_path.rstrip('/') }}(.+)$"
    replace: '\1'
  changed_when: false

- name: "Format fstab for readability"
  ansible.builtin.shell: |
    #!/bin/bash
    set -eo pipefail
    export FSTAB_GENERATED={{ fstab_generator_dir.path }}/fstab.generated
    export FSTAB_FORMATTED={{ fstab_generator_dir.path }}/fstab.formatted
    cat $FSTAB_GENERATED | grep -v '^#' | column -t > $FSTAB_FORMATTED
  args:
    executable: /bin/bash
  changed_when: false

- name: "Replace current fstab w/ generated fstab file"
  ansible.builtin.copy:
    src: "{{ fstab_generator_dir.path }}/fstab.formatted"
    dest: "{{ system_root_mount_path }}/etc/fstab"
    owner: root
    group: root
    mode: "644"
    remote_src: true
  become: true

- name: "Deleted temp file(s)"
  ansible.builtin.file:
    path: "{{ fstab_generator_dir.path }}"
    state: absent
  changed_when: false
