---
default_system_packages:
  baseline:
  - apt-transport-https
  - bsdextrautils
  - btrfs-progs
  - ca-certificates
  - curl
  - dnsutils
  - dosfstools
  - e2fsprogs
  - fdisk
  - gnupg
  - jq
  - less
  - lsof
  - netcat-openbsd
  - net-tools
  - openssl
  - open-iscsi
  - parted
  - wget
  - zstd
  by_release:
    "20.04": []
    "22.04": "{{ (device_type == 'raspi') ? ['linux-modules-extra-raspi'] : [] }}"
    "24.04": []

boot_firmware_dest:
  raspi: /boot/firmware
  any: /boot
