---
default_system_packages:
  baseline:
  - apt-transport-https
  - bsdextrautils
  - btrfs-progs
  - ca-certificates
  - curl
  - dnsutils
  - dosfstools
  - e2fsprogs
  - fdisk
  - gnupg
  - jq
  - less
  - lsof
  - netcat-openbsd
  - net-tools
  - openssl
  - open-iscsi
  - parted
  - wget
  - zstd
  by_release:
    "20.04": []
    "22.04": [linux-modules-extra-raspi]

device_type: any

boot_firmware_dest:
  raspi: /boot/firmware
  any: /boot

kernel_age_seconds: 0
initramfs_age_seconds: 0
