---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
- name: instance
  image: ${MOLECULE_IMAGE:-"geerlingguy/docker-ubuntu2204-ansible:latest"}
  pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    verify: ../install_from_url.package_as_archive/verify.yml
verifier:
  name: ansible
