---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
  - name: "Create needed directories"
    ansible.builtin.file:
      path: "{{ item }}"
      owner: root
      group: root
      mode: '0750'
      state: directory
    loop:
    - /mnt/boot/focal
    - /mnt/boot/jammy
    - /mnt/boot/noble
