---
- name: "check-status | Wait till node is operational"
  kubernetes.core.k8s_info:
    kubeconfig: "{{ k3s.kubeconfig_location | mandatory }}"
    kind: Node
    label_selectors:
    - "kubernetes.io/hostname={{ ansible_hostname }}"
    wait: true
    wait_condition:
      reason: KubeletReady
      status: "True"
      type: Ready
    wait_timeout: 180

- name: "check-status | Wait till not-ready taint is removed"
  kubernetes.core.k8s_info:
    kubeconfig: "{{ k3s.kubeconfig_location | mandatory }}"
    kind: Node
    label_selectors:
    - "kubernetes.io/hostname={{ ansible_hostname }}"
  register: install_k3s_service_node_status
    # yamllint disable-line rule:line-length
  until: "'node.kubernetes.io/not-ready' not in (install_k3s_service_node_status.resources | map(attribute='spec.taints') | flatten | map(attribute='key'))"
  retries: 5
  delay: 10

- name: "check-status | Show node status"
  debug:
    msg: "{{ install_k3s_service_node_status | community.general.json_query(query) | flatten }}"
  vars:
    # yamllint disable-line rule:line-length
    query: "resources[*].{created: metadata.creationTimestamp, name: metadata.name, labels: metadata.labels, status: status.conditions[*].join('=', [type,status]), taints: spec.taints[*].join('=', [key,effect])}"  # noqa: var-naming[no-role-prefix]
  when: verbose >= 1
