---
- name: "init-agent-node | Write agent token to temp file"
  ansible.builtin.copy:
    content: "{{ k3s.tokens['agent'] }}"
    dest: "/tmp/k3s_token_agent"
    owner: root
    group: root
    mode: '0600'
  no_log: true

- name: "init-agent-node | Initializing agent to join cluster: {{ k3s.discovery_url }}"
  ansible.builtin.shell: |
    #!/bin/bash
    set -eo pipefail
    export INSTALL_K3S_SKIP_DOWNLOAD=true
    export K3S_URL={{ k3s.discovery_url }}
    # on agent nodes, only 'agent-token' needs to be set
    export K3S_TOKEN_FILE=/tmp/k3s_token_agent
    # all other parameters are set in /etc/rancher/k3s/config.yaml
    cat /root/k3s-install.sh | sh -s - agent
    touch /etc/rancher/k3s/status/k3s.agent.initialized
  when: k3s.discovery_url|length > 0
  args:
    executable: /bin/bash
    creates: /etc/rancher/k3s/status/k3s.agent.initialized

- name: "init-agent-node | Remove temp token files"
  ansible.builtin.file:
    path: "/tmp/k3s_token_agent"
    state: absent
