---
- name: Converge
  hosts: instance
  become: true
  gather_facts: true

  vars:
    system_packages:
      baseline:
      - apt-transport-https
      - bsdextrautils
      - btrfs-progs
      - ca-certificates
      - curl
      - dnsutils
      - dosfstools
      - e2fsprogs
      - fdisk
      - gnupg
      - jq
      - less
      - lsof
      - netcat-openbsd
      - net-tools
      - openssl
      - open-iscsi
      - parted
      - vim
      - wget
      - zstd
      by_release:
        focal:
          raspi: []
          any: []
        jammy:
          raspi: ['linux-modules-extra-raspi']
          any: []
        noble:
          raspi: []
          any: []

  tasks:
  - name: "Setup Ubuntu OS"
    ansible.builtin.include_role:
      name: homelab_ops.os.ubuntu
    vars:
      ubuntu:
        initrd:
          iscsi_root_fs_enabled: true
        kernel:
          modules:
          - br_netfilter
          - overlay
          - iscsi_tcp
          parameters:
            net.ipv4.ip_forward: 1
            net.ipv6.conf.all.forwarding: 1
          upgrade: true
        packages:
          install: "{{ system_packages.baseline + system_packages.by_release[ansible_distribution_release][device_type] }}"
          remove:
          - name: snapd
            systemd_services: [snapd]
            directories:
            - /snap
            - /var/snap
            - /var/lib/snapd
            - /var/cache/snapd
            - /usr/lib/snapd
            - /root/snap
            reinstall: prevent
          - name: squashfs-tools
          - name: unattended-upgrades
            systemd_services: [unattended-upgrades]
            reinstall: prevent
        services:
          mask:
          - apt-daily-upgrade.service
          - apt-daily.service
          disable:
          - apt-daily-upgrade.timer
          - apt-daily.timer
