---
- name: Prepare
  hosts: controller
  become: true
  gather_facts: false
  tasks:
  - name: "Fetch and unpack image"
    ansible.builtin.shell: >-
      scripts/fetch-image.sh
      --url {{ image_url }}
      --output {{ image_file }}
      --timeout 2m
    args:
      executable: /bin/bash

  - name: "Mount image onto system root directory"
    ansible.builtin.shell: >-
      scripts/mount-image.sh
      --image {{ image_file }}
      --system-root {{ system_root_mount }}
      --boot-root {{ boot_firmware_source }}
    args:
      executable: /bin/bash

  - name: "Device[raspi] | Re-locate boot firmware from mounted boot partition to expected location"
    when: device_type == "raspi" and boot_firmware_source != "-"
    ansible.builtin.copy:
      # src has trailing slash so that contents of directory will be copied instead of directory as well
      src: "{{ system_root_mount }}/{{ boot_firmware_source }}/"
      dest: "{{ system_root_mount }}/boot/firmware"
      remote_src: true
      owner: root
      group: root
      mode: '0755'

  - name: "Removing existing resolv conf"
    ansible.builtin.file:
      path: "{{ system_root_mount }}/etc/resolv.conf"
      state: absent

  - name: "Creating temporary resolv conf"
    ansible.builtin.copy:
      content: 'nameserver 1.1.1.1'
      dest: "{{ system_root_mount }}/etc/resolv.conf"
      owner: root
      group: root
      mode: '0644'
