---
tls-san: "kubernetes-api.example.com"
flannel-backend: wireguard-native

disable:
- local-storage
- servicelb
- traefik

node-taint:
- 'node-role.kubernetes.io/control-plane=true:NoSchedule'

prefer-bundled-bin: true
