---
- name: "configure-uncompressed-kernel | Copy the uncompress script to boot partition directory"
  ansible.builtin.template:
    src: auto_uncompress_kernel.sh.j2
    dest: "{{ boot_firmware_dest[device_type] }}/auto_uncompress_kernel.sh"
    owner: root
    group: root
    mode: '0750'

- name: "configure-uncompressed-kernel | Configure dpkg to automatically uncompress kernels installed in the future"
  ansible.builtin.template:
    src: uncompress_kernel.apt.conf.j2
    dest: /etc/apt/apt.conf.d/999_uncompress_rpi_kernel
    owner: root
    group: root
    mode: '0644'
