---
- name: "install-packages | Install latest versions of selected packages"
  when: ubuntu.packages.install|length > 0
  ansible.builtin.include_role:
    name: "homelab_ops.packages.apt_install"
  vars:
    packages: "{{ ubuntu.packages.install }}"
