---
- name: "pre-requisites | Ensure boot partition mount exists"
  ansible.builtin.file:
    path: "{{ boot_firmware_dest[device_type] }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: "pre-requisites | Detect installed kernel (not the current kernel booted under)"
  ansible.builtin.import_tasks: detect-kernel-version.yaml
