---
- name: "uncompress-kernel | Read kernel uncompressed marker"
  ansible.builtin.stat:
    path: "{{ boot_firmware_dest[device_type] }}/kernel.uncompressed.marker"
  register: stat_kernel_uncompressed_marker

- name: "uncompress-kernel | Uncompress the current kernel if marker does not exist"
  when: not stat_kernel_uncompressed_marker.stat.exists
  ansible.builtin.command: "{{ boot_firmware_dest[device_type] }}/auto_uncompress_kernel.sh"
  register: kernel_uncompress

- name: Record that kernel was uncompressed with a marker file
  when: kernel_uncompress.changed
  ansible.builtin.file:
    path: "{{ boot_firmware_dest[device_type] }}/kernel.uncompressed.marker"
    state: touch
