---
- name: "update-initramfs | Indicate that iscsi support should be available within initramfs for use at boot time"
  when: "{{ ubuntu.initrd.iscsi_root_fs_enabled | default(false) }}"
  ansible.builtin.file:
    path: /etc/iscsi/iscsi.initramfs
    state: touch
    owner: root
    group: root
    mode: '0644'
  changed_when: false

- name: "update-initramfs | Detect installed kernel (not the current kernel booted under)"
  ansible.builtin.import_tasks: detect-kernel-version.yaml

- name: "update-initramfs | read the current initramfs initialized marker"
  ansible.builtin.stat:
    path: "{{ boot_firmware_dest[device_type] }}/initrd.initialized.marker"
  register: stat_initramfs_marker

- name: "update-initramfs | Create a new initramfs for kernel: {{ current_kernel_version }}"
  when: not stat_initramfs_marker.stat.exists
  ansible.builtin.command: "update-initramfs -v -k {{ current_kernel_version }} -c"
  register: initramfs

- name: Record that initramfs was initialized with a marker file
  when: initramfs.changed
  ansible.builtin.file:
    path: "{{ boot_firmware_dest[device_type] }}/initrd.initialized.marker"
    state: touch

- name: "update-initramfs | Read the new initramfs symlink"
  when: initramfs.changed
  ansible.builtin.stat:
    path: "/boot/initrd.img"
  register: stat_initrd

- name: "update-initramfs | Place the new initramfs under boot partition mount"
  when: initramfs.changed
  ansible.builtin.copy:
    src: "{{ stat_initrd.stat.lnk_source }}"
    dest: "{{ boot_firmware_dest[device_type] }}/initrd.img"
    owner: root
    group: root
    mode: '0755'
    remote_src: true
