---
- name: "install | check for pre-requisites"
  ansible.builtin.command: "flux check --pre --kubeconfig {{ flux.kubeconfig_location | mandatory }}"
  changed_when: false

- name: "install | install flux into kubernetes cluster"
  ansible.builtin.command: >
    flux install
    --version v{{ flux.version }}
    --kubeconfig {{ flux.kubeconfig_location | mandatory }}
    --toleration-keys=node-role.kubernetes.io/control-plane

- name: "install | check that flux installation is healthy"
  ansible.builtin.command: flux check --kubeconfig {{ flux.kubeconfig_location | mandatory }}
  changed_when: false
