---
- name: "configure-cloudinit | set up cloud init"
  ansible.builtin.include_role:
    name: homelab_ops.configure.cloud_init
  vars:
    cloudinit:
      # place data source under boot filesystem mount path
      data_source_path: "{{ partition_mount_points['boot'].current }}"
      local_hostname: "{{ provision.raspberry_pi.hostname | default(default_hostname) }}"
      instance_id: "{{ provision.raspberry_pi.instance_id | default(default_instance_id) }}"
      users: "{{ provision.cloudinit.ssh_users }}"
      runcmd_commands: "{{ provision.cloudinit.runcmd_commands | default([]) }}"
      write_files: "{{ provision.cloudinit.write_files | default([]) }}"
