---
- name: "image-block-device | provision block device from OS image"
  ansible.builtin.include_role:
    name: homelab_ops.archive.sync
  vars:
    archive:
      url: "{{ provision.os_image.url }}"
      destination_path: "{{ system_root_mount_point }}"
      extracted_size: "{{ ram_disk_size | default('3072M') }}"
      exclude_paths:
      - /boot/firmware/cmdline.txt
      - /boot/firmware/config.txt
      - /boot/firmware/user-data
      - /boot/firmware/meta-data
      - /boot/firmware/vendor-data
      - /etc/fstab
      quiet: true
