---
---
- name: "Check for mandatory variables definitions"
  assert:
    that:
    - provision is defined and provision|length > 0
    - provision.block_device is defined and provision.block_device|length > 0
    - provision.os_image is defined and provision.os_image|length > 0
    - provision.os_image.url is defined and provision.os_image.url is url
    - provision.os_image.distribution_release is defined
    - provision.raspberry_pi.serial is defined and provision.raspberry_pi.serial|length == 8
    - provision.cloudinit.ssh_users is defined and provision.cloudinit.ssh_users|length > 0

- name: Provision block device
  ansible.builtin.import_tasks: provision-block-device.yaml

- name: Image block device
  ansible.builtin.import_tasks: image-block-device.yaml

- name: Configure cloud init
  ansible.builtin.import_tasks: configure-cloudinit.yaml

- name: Configure for booting
  ansible.builtin.import_tasks: configure-boot.yaml
