---
- name: Converge
  hosts: all
  gather_facts: false
  vars:
    unpack_location: /tmp/unpack_location
  tasks:
  - name: "Fetch and unpack archive"
    ansible.builtin.include_role:
      name: homelab_ops.archive.sync
    vars:
      archive:
        url: "{{ config.ubuntu_url }}"
        destination_path: "{{ unpack_location }}"
        extracted_size: "100M"
