---
- name: Converge
  hosts: all
  gather_facts: false
  vars:
    cloudinit_seed_path: "/mnt/cloudinit"
  tasks:
  - name: "Configure cloud init"
    ansible.builtin.include_role:
      name: homelab_ops.configure.cloud_init
    vars:
      cloudinit:
        data_source_path: "{{ cloudinit_seed_path }}"
        local_hostname: test-hostname
        instance_id: test-instance
        users:
        - name: test-user
          authorized_keys:
          - ssh-ed25519 AAAABBBBCCCCDDDDEEEEFFFF test-user@email.com
        ansible_playbook: "playbook.yaml"
        ansible_vars_file: "vars.yaml"
