---
- name: Converge
  hosts: all
  gather_facts: false
  vars:
    data_source_path: "/mnt/cloudinit"
  tasks:
  - name: "Configure cloud init"
    ansible.builtin.include_role:
      name: homelab_ops.configure.cloud_init
    vars:
      cloudinit:
        data_source_path: "{{ data_source_path }}"
        local_hostname: test-hostname
        instance_id: test-instance
        users:
        - name: test-user
          authorized_keys:
          - ssh-ed25519 AAAABBBBCCCCDDDDEEEEFFFF test-user@email.com
        runcmd_commands:
        - "[timedatectl, set-ntp, 'true']"
        - "[ANSIBLE_LOCALHOST_WARNING=false, ansible-playbook, -c, local, -i, localhost, /playbook.yaml, -e, '@/playbook-vars.yaml']"
        write_files:
        - path: /playbook.yaml
          owner: 'root:root'
          permissions: '0600'
          # yamllint disable-line rule:indentation
          content: |
            ---
            - name: "Example playbook"
              hosts: localhost
              become: true
              gather_facts: true
              tasks:
              - name: "Example task"
                ansible.builtin.debug:
                  msg: "Example"
        - path: /playbook-vars.yaml
          owner: 'root:root'
          permissions: '0600'
          content: |
            ---
            # example file with variables for the ansible-playbook
            a: b
            c: d
            e: f
