---
name: Release

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    name: "create release"
    steps:
    - name: Check out
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      with:
        token: "${{ secrets.GH_RELEASE_TOKEN }}"
        fetch-depth: 0

    - name: Set up python
      uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: |
          requirements.txt

    - name: Install python requirements
      run: python -m pip install -r requirements.txt

    - name: Set up node
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
      with:
        node-version: 20

    - name: Install node packages
      run: npm ci

    - name: Release
      run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}

    - name: Determine release version
      run: echo "RELEASED_VERSION=$(cat /tmp/released.version | cut -d'v' -f2)" >> $GITHUB_ENV
