---
- name: create first cluster node
  hosts: node1-server
  become: true
  gather_facts: true
  tasks:
  - name: install k3s service
    ansible.builtin.include_role:
      name: homelab_ops.k3s.install_k3s_service
    vars:
      k3s:  # noqa: var-naming[no-role-prefix]
        version: "{{ config.k3s_version }}"
        discovery_url: ~
        node:
          type: server
          config: "{{ config.node_config_directory }}/server.yaml"
        tokens:
          server: "{{ config.server_token }}"
          agent: "{{ config.agent_token }}"
        hardening:
          enabled: "{{ config.hardening }}"
        expose_metrics: "{{ config.metrics_exposed }}"
        local_kubeconfig: "{{ config.local_kubeconfig }}"
  - name: "install flux service"
    ansible.builtin.include_role:
      name: homelab_ops.k3s.install_flux_service
    vars:
      flux:  # noqa: var-naming[no-role-prefix]
        version: "{{ config.flux_version }}"
        local_kubeconfig: "{{ config.local_kubeconfig }}"
      kustomize:  # noqa: var-naming[no-role-prefix]
        version: "{{ config.kustomize_version }}"

- name: create the remaining cluster nodes
  hosts:
  - node2-server
  - node3-agent
  become: true
  gather_facts: true
  vars:
    node_type: "{{ inventory_hostname | split('-') | last }}"
  tasks:
  - name: install k3s service
    ansible.builtin.include_role:
      name: homelab_ops.k3s.install_k3s_service
    vars:
      k3s:  # noqa: var-naming[no-role-prefix]
        version: "{{ config.k3s_version }}"
        discovery_url: https://node1-server:6443
        node:
          type: "{{ node_type }}"
          config: "{{ config.node_config_directory }}/{{ node_type }}.yaml"
        tokens:
          server: "{{ config.server_token }}"
          agent: "{{ config.agent_token }}"
        hardening:
          enabled: "{{ config.hardening }}"
        expose_metrics: "{{ config.metrics_exposed }}"
        local_kubeconfig: "{{ config.local_kubeconfig }}"
  - name: "install flux service"
    when: node_type == 'server'
    ansible.builtin.include_role:
      name: homelab_ops.k3s.install_flux_service
    vars:
      flux:  # noqa: var-naming[no-role-prefix]
        version: "{{ config.flux_version }}"
        local_kubeconfig: "{{ config.local_kubeconfig }}"
      kustomize:  # noqa: var-naming[no-role-prefix]
        version: "{{ config.kustomize_version }}"

- name: create test resources
  hosts: localhost
  become: true
  gather_facts: true
  tasks:
  - name: Create test resource(s) from local file
    kubernetes.core.k8s:
      state: present
      src: "{{ config.test_resources_manifest }}"
      kubeconfig: "{{ config.local_kubeconfig }}"
