---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
- name: "node1-server"
  image: ${MOLECULE_IMAGE:-"geerlingguy/docker-ubuntu2404-ansible:latest"}
  pre_build_image: true
  exposed_ports:
  - 6443/tcp
  published_ports:
  - 0.0.0.0:6443:6443/tcp
  docker_networks:
  - name: k3s-cluster
  networks:
  - name: k3s-cluster
  command: /usr/sbin/init
  runtime: sysbox-runc
  user: root

- name: "node2-server"
  image: ${MOLECULE_IMAGE:-"geerlingguy/docker-ubuntu2404-ansible:latest"}
  pre_build_image: true
  exposed_ports:
  - 6443/tcp
  docker_networks:
  - name: k3s-cluster
  networks:
  - name: k3s-cluster
  command: /usr/sbin/init
  runtime: sysbox-runc
  user: root

- name: "node3-agent"
  image: ${MOLECULE_IMAGE:-"geerlingguy/docker-ubuntu2404-ansible:latest"}
  pre_build_image: true
  exposed_ports:
  - 6443/tcp
  docker_networks:
  - name: k3s-cluster
  networks:
  - name: k3s-cluster
  command: /usr/sbin/init
  runtime: sysbox-runc
  user: root

provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        config:
          # renovate: datasource=github-releases depName=k3s-io/k3s
          k3s_version: "1.30.2+k3s1"
          # renovate: datasource=github-releases depName=fluxcd/flux2
          flux_version: "2.4.0"
          # renovate: datasource=github-releases depName=kubernetes-sigs/kustomize
          kustomize_version: "5.4.1"
          node_config_directory: ${MOLECULE_SCENARIO_DIRECTORY}/k3s-config
          server_token: $k3s_server_token
          agent_token: $k3s_agent_token
          hardening: $hardening_enabled
          metrics_exposed: $metrics_exposed
          test_resources_manifest: ${MOLECULE_SCENARIO_DIRECTORY}/test-resources/test.yaml
          local_kubeconfig: /tmp/kubeconfig/k3s

verifier:
  name: ansible
