---
- name: Verify cluster
  hosts: localhost
  gather_facts: false
  vars:
    required_nodes:
    - node1-server
    - node2-server
    - node3-agent
    local_kubeconfig: /tmp/kubeconfig/k3s
  pre_tasks:
  - name: Load required pods
    ansible.builtin.include_vars: vars/expected-pods.yml
  - name: Load required api
    ansible.builtin.include_vars: vars/expected-api.yml
  - name: Load required resources
    ansible.builtin.include_vars: vars/expected-resources.yml

  tasks:
  - name: verify cluster nodes
    ansible.builtin.import_tasks: verify/cluster-node-checks.yml

  - name: verify cluster pods
    ansible.builtin.import_tasks: verify/cluster-pod-checks.yml

  - name: verify cluster api
    ansible.builtin.import_tasks: verify/cluster-api-checks.yml

  - name: verify test resources
    ansible.builtin.import_tasks: verify/kubernetes-resource-checks.yml
